<?php

namespace App\Console\Commands;

use App\Models\Menu;
use Illuminate\Console\Command;

class TranslateMenuToVietnamese extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'menu:translate-to-vietnamese';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Dịch tất cả tên món và mô tả menu sang tiếng Việt';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->info('Bắt đầu dịch menu sang tiếng Việt...');

        $menus = Menu::all();
        $bar = $this->output->createProgressBar($menus->count());
        $bar->start();

        $translated = 0;
        foreach ($menus as $menu) {
            try {
                // Dịch tên món (giới hạn 50 ký tự)
                $translatedName = $this->translateText($menu->name);
                $translatedName = mb_substr($translatedName, 0, 50);
                
                // Dịch mô tả (giới hạn 255 ký tự)
                $translatedDescription = $this->translateText($menu->description ?? '');
                $translatedDescription = mb_substr($translatedDescription, 0, 255);
                
                // Cập nhật database
                $menu->update([
                    'name' => $translatedName,
                    'description' => $translatedDescription
                ]);
                
                $translated++;
            } catch (\Exception $e) {
                $this->error("Lỗi khi dịch món ID {$menu->id}: " . $e->getMessage());
            }
            
            $bar->advance();
        }

        $bar->finish();
        $this->newLine();
        $this->info("Đã dịch {$translated} món ăn sang tiếng Việt!");

        return Command::SUCCESS;
    }

    /**
     * Dịch text sang tiếng Việt
     * 
     * @param string $text
     * @return string
     */
    private function translateText($text)
    {
        // Dictionary các cụm từ phổ biến (ưu tiên dịch cụm từ trước)
        $phraseTranslations = [
            'Choose from a variety of' => 'Chọn từ nhiều loại',
            'Available in' => 'Có sẵn trong',
            'Served with' => 'Kèm theo',
            'Made with' => 'Làm từ',
            'Topped with' => 'Phủ lên trên',
            'Filled with' => 'Nhân',
            'Order of' => 'Phần',
            'Comes in' => 'Có',
            'Includes' => 'Bao gồm',
            'Served' => 'Phục vụ',
            'Topped' => 'Phủ',
            'Cooked' => 'Nấu',
            'Marinated' => 'Ướp',
            'Seasoned' => 'Tẩm gia vị',
            'Sliced' => 'Cắt lát',
            'Chopped' => 'Cắt nhỏ',
            'Diced' => 'Cắt hạt lựu',
            'Shredded' => 'Xé nhỏ',
            'Ground' => 'Xay',
            'Whole' => 'Nguyên',
            'Half' => 'Nửa',
            'Quarter' => 'Một phần tư',
            'Large' => 'Lớn',
            'Medium' => 'Vừa',
            'Small' => 'Nhỏ',
            'Extra' => 'Thêm',
            'Double' => 'Gấp đôi',
            'Triple' => 'Gấp ba',
            'Combo' => 'Combo',
            'Meal' => 'Bữa ăn',
            'Plate' => 'Đĩa',
            'Platter' => 'Khay',
            'Bucket' => 'Xô',
            'Bowl' => 'Tô',
            'Cup' => 'Cốc',
            'Glass' => 'Ly',
            'Bottle' => 'Chai',
            'Can' => 'Lon',
            'Box' => 'Hộp',
            'Bag' => 'Túi',
            'Pack' => 'Gói',
            'Piece' => 'Miếng',
            'Pieces' => 'Miếng',
            'Pcs' => 'Miếng',
            'Pc' => 'Miếng',
            'mL' => 'ml',
            'Litre' => 'Lít',
            'and' => 'và',
            'or' => 'hoặc',
            'with' => 'với',
            'without' => 'không có',
            'of' => 'của',
            'your' => 'của bạn',
            'our' => 'của chúng tôi',
            'choice' => 'lựa chọn',
            'sauce' => 'sốt',
            'sauces' => 'sốt',
            'dressing' => 'nước sốt',
            'dressings' => 'nước sốt',
            'cheese' => 'phô mai',
            'meat' => 'thịt',
            'chicken' => 'gà',
            'beef' => 'thịt bò',
            'pork' => 'thịt heo',
            'fish' => 'cá',
            'shrimp' => 'tôm',
            'vegetables' => 'rau củ',
            'vegetable' => 'rau củ',
            'lettuce' => 'rau xà lách',
            'tomato' => 'cà chua',
            'tomatoes' => 'cà chua',
            'onion' => 'hành tây',
            'onions' => 'hành tây',
            'pepper' => 'ớt',
            'peppers' => 'ớt',
            'mushroom' => 'nấm',
            'mushrooms' => 'nấm',
            'olive' => 'ô liu',
            'olives' => 'ô liu',
            'pickle' => 'dưa chua',
            'pickles' => 'dưa chua',
            'bacon' => 'thịt xông khói',
            'sausage' => 'xúc xích',
            'bread' => 'bánh mì',
            'bun' => 'bánh mì',
            'buns' => 'bánh mì',
            'rice' => 'cơm',
            'noodles' => 'mì',
            'pasta' => 'mì ống',
            'potato' => 'khoai tây',
            'potatoes' => 'khoai tây',
            'fries' => 'khoai tây chiên',
            'poutine' => 'poutine',
            'salad' => 'salad',
            'soup' => 'súp',
            'pizza' => 'pizza',
            'burger' => 'burger',
            'sandwich' => 'bánh mì sandwich',
            'wings' => 'cánh gà',
            'dessert' => 'tráng miệng',
            'beverage' => 'đồ uống',
            'drink' => 'đồ uống',
            'drinks' => 'đồ uống',
            'coffee' => 'cà phê',
            'tea' => 'trà',
            'juice' => 'nước ép',
            'soda' => 'nước ngọt',
            'water' => 'nước',
            'ice' => 'đá',
            'cream' => 'kem',
            'ice cream' => 'kem',
            'cake' => 'bánh',
            'cakes' => 'bánh',
            'cookie' => 'bánh quy',
            'cookies' => 'bánh quy',
            'pie' => 'bánh',
            'pies' => 'bánh',
            'tart' => 'bánh tart',
            'tarts' => 'bánh tart',
            'muffin' => 'bánh muffin',
            'muffins' => 'bánh muffin',
            'donut' => 'bánh donut',
            'donuts' => 'bánh donut',
            'breadstick' => 'bánh mì que',
            'breadsticks' => 'bánh mì que',
            'cracker' => 'bánh quy giòn',
            'crackers' => 'bánh quy giòn',
            'chip' => 'khoai tây chiên',
            'chips' => 'khoai tây chiên',
            'dip' => 'nước chấm',
            'dips' => 'nước chấm',
            'spread' => 'phết',
            'spreads' => 'phết',
            'butter' => 'bơ',
            'margarine' => 'bơ thực vật',
            'oil' => 'dầu',
            'vinegar' => 'giấm',
            'salt' => 'muối',
            'pepper' => 'tiêu',
            'sugar' => 'đường',
            'honey' => 'mật ong',
            'syrup' => 'siro',
            'jam' => 'mứt',
            'jelly' => 'thạch',
            'peanut butter' => 'bơ đậu phộng',
            'nutella' => 'nutella',
            'mayonnaise' => 'mayonnaise',
            'mustard' => 'mù tạt',
            'ketchup' => 'tương cà',
            'relish' => 'dưa chua',
            'hot sauce' => 'sốt cay',
            'bbq sauce' => 'sốt bbq',
            'ranch' => 'ranch',
            'caesar' => 'caesar',
            'italian' => 'ý',
            'french' => 'pháp',
            'greek' => 'hy lạp',
            'asian' => 'châu á',
            'mexican' => 'mexico',
            'indian' => 'ấn độ',
            'chinese' => 'trung quốc',
            'japanese' => 'nhật bản',
            'thai' => 'thái lan',
            'korean' => 'hàn quốc',
            'vietnamese' => 'việt nam',
            'american' => 'mỹ',
            'canadian' => 'canada',
            'european' => 'châu âu',
            'mediterranean' => 'địa trung hải',
            'middle eastern' => 'trung đông',
            'latin' => 'mỹ latin',
            'caribbean' => 'caribbean',
            'african' => 'châu phi',
            'australian' => 'úc',
            'new zealand' => 'new zealand',
            'british' => 'anh',
            'irish' => 'ireland',
            'scottish' => 'scotland',
            'welsh' => 'wales',
            'german' => 'đức',
            'spanish' => 'tây ban nha',
            'portuguese' => 'bồ đào nha',
            'italian' => 'ý',
            'french' => 'pháp',
            'greek' => 'hy lạp',
            'turkish' => 'thổ nhĩ kỳ',
            'russian' => 'nga',
            'polish' => 'ba lan',
            'czech' => 'séc',
            'hungarian' => 'hungary',
            'romanian' => 'romania',
            'bulgarian' => 'bulgaria',
            'serbian' => 'serbia',
            'croatian' => 'croatia',
            'slovenian' => 'slovenia',
            'slovak' => 'slovakia',
            'ukrainian' => 'ukraine',
            'belarusian' => 'belarus',
            'lithuanian' => 'lithuania',
            'latvian' => 'latvia',
            'estonian' => 'estonia',
            'finnish' => 'phần lan',
            'swedish' => 'thụy điển',
            'norwegian' => 'na uy',
            'danish' => 'đan mạch',
            'icelandic' => 'iceland',
            'dutch' => 'hà lan',
            'belgian' => 'bỉ',
            'swiss' => 'thụy sĩ',
            'austrian' => 'áo',
            'luxembourgish' => 'luxembourg',
            'monaco' => 'monaco',
            'liechtenstein' => 'liechtenstein',
            'andorra' => 'andorra',
            'san marino' => 'san marino',
            'vatican' => 'vatican',
            'malta' => 'malta',
            'cyprus' => 'síp',
            'israel' => 'israel',
            'palestine' => 'palestine',
            'lebanon' => 'lebanon',
            'syria' => 'syria',
            'jordan' => 'jordan',
            'iraq' => 'iraq',
            'iran' => 'iran',
            'saudi arabia' => 'ả rập saudi',
            'uae' => 'uae',
            'qatar' => 'qatar',
            'kuwait' => 'kuwait',
            'bahrain' => 'bahrain',
            'oman' => 'oman',
            'yemen' => 'yemen',
            'afghanistan' => 'afghanistan',
            'pakistan' => 'pakistan',
            'bangladesh' => 'bangladesh',
            'sri lanka' => 'sri lanka',
            'nepal' => 'nepal',
            'bhutan' => 'bhutan',
            'myanmar' => 'myanmar',
            'laos' => 'laos',
            'cambodia' => 'campuchia',
            'malaysia' => 'malaysia',
            'singapore' => 'singapore',
            'indonesia' => 'indonesia',
            'philippines' => 'philippines',
            'brunei' => 'brunei',
            'east timor' => 'đông timor',
            'mongolia' => 'mongolia',
            'north korea' => 'bắc triều tiên',
            'south korea' => 'hàn quốc',
            'taiwan' => 'đài loan',
            'hong kong' => 'hồng kông',
            'macau' => 'macau',
            'brazil' => 'brazil',
            'argentina' => 'argentina',
            'chile' => 'chile',
            'peru' => 'peru',
            'colombia' => 'colombia',
            'venezuela' => 'venezuela',
            'ecuador' => 'ecuador',
            'bolivia' => 'bolivia',
            'paraguay' => 'paraguay',
            'uruguay' => 'uruguay',
            'guyana' => 'guyana',
            'suriname' => 'suriname',
            'french guiana' => 'guiana thuộc pháp',
            'falkland islands' => 'quần đảo falkland',
            'south georgia' => 'nam georgia',
            'south sandwich islands' => 'quần đảo nam sandwich',
            'south orkney islands' => 'quần đảo nam orkney',
            'south shetland islands' => 'quần đảo nam shetland',
            'antarctica' => 'nam cực',
            'greenland' => 'greenland',
            'iceland' => 'iceland',
            'faroe islands' => 'quần đảo faroe',
            'svalbard' => 'svalbard',
            'jan mayen' => 'jan mayen',
            'bear island' => 'đảo bear',
            'hopen' => 'hopen',
            'kvitoya' => 'kvitoya',
            'kong karls land' => 'đất kong karls',
            'edgeoya' => 'edgeoya',
            'barentsoya' => 'barentsoya',
            'prins karls forland' => 'prins karls forland',
            'bjornoya' => 'bjornoya',
            'hopen' => 'hopen',
            'kvitoya' => 'kvitoya',
            'kong karls land' => 'đất kong karls',
            'edgeoya' => 'edgeoya',
            'barentsoya' => 'barentsoya',
            'prins karls forland' => 'prins karls forland',
            'bjornoya' => 'bjornoya',
        ];

        // Dictionary các từ thường dùng
        $translations = [
            // Tên món phổ biến
            'Pizza' => 'Pizza',
            'Chicken' => 'Gà',
            'Burger' => 'Burger',
            'Salad' => 'Salad',
            'Fries' => 'Khoai tây chiên',
            'Soup' => 'Súp',
            'Pasta' => 'Mì ống',
            'Sandwich' => 'Bánh mì sandwich',
            'Wings' => 'Cánh gà',
            'Dessert' => 'Tráng miệng',
            'Beverage' => 'Đồ uống',
            'Sushi' => 'Sushi',
            'Shawarma' => 'Shawarma',
            
            // Mô tả thường dùng
            'Choose from' => 'Chọn từ',
            'Available in' => 'Có sẵn trong',
            'Served with' => 'Kèm theo',
            'Made with' => 'Làm từ',
            'Topped with' => 'Phủ lên trên',
            'Fresh' => 'Tươi',
            'Crispy' => 'Giòn',
            'Grilled' => 'Nướng',
            'Fried' => 'Chiên',
            'Baked' => 'Nướng',
            'Steamed' => 'Hấp',
            'Spicy' => 'Cay',
            'Sweet' => 'Ngọt',
            'Sour' => 'Chua',
            'Creamy' => 'Kem',
            'Tender' => 'Mềm',
            'Juicy' => 'Nhiều nước',
            'Classic' => 'Cổ điển',
            'Traditional' => 'Truyền thống',
            'Homemade' => 'Tự làm',
            'Special' => 'Đặc biệt',
            'Delicious' => 'Ngon',
            'Flavorful' => 'Đậm đà',
            'Healthy' => 'Tốt cho sức khỏe',
            'Vegetarian' => 'Chay',
            'Vegan' => 'Thuần chay',
            'Gluten free' => 'Không gluten',
            'pieces' => 'miếng',
            'piece' => 'miếng',
            'pcs' => 'miếng',
            'pc' => 'miếng',
            'mL' => 'ml',
            'Litre' => 'Lít',
            'Bottle' => 'Chai',
            'Can' => 'Lon',
            'Box' => 'Hộp',
            'Order of' => 'Phần',
            'Comes in' => 'Có',
            'Includes' => 'Bao gồm',
            'Served' => 'Phục vụ',
            'Topped' => 'Phủ',
            'Filled with' => 'Nhân',
            'Cooked' => 'Nấu',
            'Marinated' => 'Ướp',
            'Seasoned' => 'Tẩm gia vị',
            'Sliced' => 'Cắt lát',
            'Chopped' => 'Cắt nhỏ',
            'Diced' => 'Cắt hạt lựu',
            'Shredded' => 'Xé nhỏ',
            'Ground' => 'Xay',
            'Whole' => 'Nguyên',
            'Half' => 'Nửa',
            'Quarter' => 'Một phần tư',
            'Large' => 'Lớn',
            'Medium' => 'Vừa',
            'Small' => 'Nhỏ',
            'Extra' => 'Thêm',
            'Double' => 'Gấp đôi',
            'Triple' => 'Gấp ba',
            'Combo' => 'Combo',
            'Meal' => 'Bữa ăn',
            'Plate' => 'Đĩa',
            'Platter' => 'Khay',
            'Bucket' => 'Xô',
            'Bowl' => 'Tô',
            'Cup' => 'Cốc',
            'Glass' => 'Ly',
            'Bottle' => 'Chai',
            'Can' => 'Lon',
            'Box' => 'Hộp',
            'Bag' => 'Túi',
            'Pack' => 'Gói',
            'Piece' => 'Miếng',
            'Pieces' => 'Miếng',
            'Pcs' => 'Miếng',
            'Pc' => 'Miếng',
            'and' => 'và',
            'or' => 'hoặc',
            'with' => 'với',
            'without' => 'không có',
            'of' => 'của',
            'the' => '',
            'a' => '',
            'an' => '',
            'your' => 'của bạn',
            'our' => 'của chúng tôi',
            'choice' => 'lựa chọn',
            'sauce' => 'sốt',
            'sauces' => 'sốt',
            'dressing' => 'nước sốt',
            'dressings' => 'nước sốt',
            'cheese' => 'phô mai',
            'meat' => 'thịt',
            'chicken' => 'gà',
            'beef' => 'thịt bò',
            'pork' => 'thịt heo',
            'fish' => 'cá',
            'shrimp' => 'tôm',
            'vegetables' => 'rau củ',
            'vegetable' => 'rau củ',
            'lettuce' => 'rau xà lách',
            'tomato' => 'cà chua',
            'tomatoes' => 'cà chua',
            'onion' => 'hành tây',
            'onions' => 'hành tây',
            'pepper' => 'ớt',
            'peppers' => 'ớt',
            'mushroom' => 'nấm',
            'mushrooms' => 'nấm',
            'olive' => 'ô liu',
            'olives' => 'ô liu',
            'pickle' => 'dưa chua',
            'pickles' => 'dưa chua',
            'bacon' => 'thịt xông khói',
            'sausage' => 'xúc xích',
            'bread' => 'bánh mì',
            'bun' => 'bánh mì',
            'buns' => 'bánh mì',
            'rice' => 'cơm',
            'noodles' => 'mì',
            'pasta' => 'mì ống',
            'potato' => 'khoai tây',
            'potatoes' => 'khoai tây',
            'fries' => 'khoai tây chiên',
            'poutine' => 'poutine',
            'salad' => 'salad',
            'soup' => 'súp',
            'pizza' => 'pizza',
            'burger' => 'burger',
            'sandwich' => 'bánh mì sandwich',
            'wings' => 'cánh gà',
            'dessert' => 'tráng miệng',
            'beverage' => 'đồ uống',
            'drink' => 'đồ uống',
            'drinks' => 'đồ uống',
            'coffee' => 'cà phê',
            'tea' => 'trà',
            'juice' => 'nước ép',
            'soda' => 'nước ngọt',
            'water' => 'nước',
            'ice' => 'đá',
            'cream' => 'kem',
            'ice cream' => 'kem',
            'cake' => 'bánh',
            'cakes' => 'bánh',
            'cookie' => 'bánh quy',
            'cookies' => 'bánh quy',
            'pie' => 'bánh',
            'pies' => 'bánh',
            'tart' => 'bánh tart',
            'tarts' => 'bánh tart',
            'muffin' => 'bánh muffin',
            'muffins' => 'bánh muffin',
            'donut' => 'bánh donut',
            'donuts' => 'bánh donut',
            'breadstick' => 'bánh mì que',
            'breadsticks' => 'bánh mì que',
            'cracker' => 'bánh quy giòn',
            'crackers' => 'bánh quy giòn',
            'chip' => 'khoai tây chiên',
            'chips' => 'khoai tây chiên',
            'dip' => 'nước chấm',
            'dips' => 'nước chấm',
            'spread' => 'phết',
            'spreads' => 'phết',
            'butter' => 'bơ',
            'margarine' => 'bơ thực vật',
            'oil' => 'dầu',
            'vinegar' => 'giấm',
            'salt' => 'muối',
            'pepper' => 'tiêu',
            'sugar' => 'đường',
            'honey' => 'mật ong',
            'syrup' => 'siro',
            'jam' => 'mứt',
            'jelly' => 'thạch',
            'peanut butter' => 'bơ đậu phộng',
            'nutella' => 'nutella',
            'mayonnaise' => 'mayonnaise',
            'mustard' => 'mù tạt',
            'ketchup' => 'tương cà',
            'relish' => 'dưa chua',
            'hot sauce' => 'sốt cay',
            'bbq sauce' => 'sốt bbq',
            'ranch' => 'ranch',
            'caesar' => 'caesar',
            'italian' => 'ý',
            'french' => 'pháp',
            'greek' => 'hy lạp',
            'asian' => 'châu á',
            'mexican' => 'mexico',
            'indian' => 'ấn độ',
            'chinese' => 'trung quốc',
            'japanese' => 'nhật bản',
            'thai' => 'thái lan',
            'korean' => 'hàn quốc',
            'vietnamese' => 'việt nam',
            'american' => 'mỹ',
            'canadian' => 'canada',
            'european' => 'châu âu',
            'mediterranean' => 'địa trung hải',
            'middle eastern' => 'trung đông',
            'latin' => 'mỹ latin',
            'caribbean' => 'caribbean',
            'african' => 'châu phi',
            'australian' => 'úc',
            'new zealand' => 'new zealand',
            'british' => 'anh',
            'irish' => 'ireland',
            'scottish' => 'scotland',
            'welsh' => 'wales',
            'german' => 'đức',
            'spanish' => 'tây ban nha',
            'portuguese' => 'bồ đào nha',
            'italian' => 'ý',
            'french' => 'pháp',
            'greek' => 'hy lạp',
            'turkish' => 'thổ nhĩ kỳ',
            'russian' => 'nga',
            'polish' => 'ba lan',
            'czech' => 'séc',
            'hungarian' => 'hungary',
            'romanian' => 'romania',
            'bulgarian' => 'bulgaria',
            'serbian' => 'serbia',
            'croatian' => 'croatia',
            'slovenian' => 'slovenia',
            'slovak' => 'slovakia',
            'ukrainian' => 'ukraine',
            'belarusian' => 'belarus',
            'lithuanian' => 'lithuania',
            'latvian' => 'latvia',
            'estonian' => 'estonia',
            'finnish' => 'phần lan',
            'swedish' => 'thụy điển',
            'norwegian' => 'na uy',
            'danish' => 'đan mạch',
            'icelandic' => 'iceland',
            'dutch' => 'hà lan',
            'belgian' => 'bỉ',
            'swiss' => 'thụy sĩ',
            'austrian' => 'áo',
            'luxembourgish' => 'luxembourg',
            'monaco' => 'monaco',
            'liechtenstein' => 'liechtenstein',
            'andorra' => 'andorra',
            'san marino' => 'san marino',
            'vatican' => 'vatican',
            'malta' => 'malta',
            'cyprus' => 'síp',
            'israel' => 'israel',
            'palestine' => 'palestine',
            'lebanon' => 'lebanon',
            'syria' => 'syria',
            'jordan' => 'jordan',
            'iraq' => 'iraq',
            'iran' => 'iran',
            'saudi arabia' => 'ả rập saudi',
            'uae' => 'uae',
            'qatar' => 'qatar',
            'kuwait' => 'kuwait',
            'bahrain' => 'bahrain',
            'oman' => 'oman',
            'yemen' => 'yemen',
            'afghanistan' => 'afghanistan',
            'pakistan' => 'pakistan',
            'bangladesh' => 'bangladesh',
            'sri lanka' => 'sri lanka',
            'nepal' => 'nepal',
            'bhutan' => 'bhutan',
            'myanmar' => 'myanmar',
            'laos' => 'laos',
            'cambodia' => 'campuchia',
            'malaysia' => 'malaysia',
            'singapore' => 'singapore',
            'indonesia' => 'indonesia',
            'philippines' => 'philippines',
            'brunei' => 'brunei',
            'east timor' => 'đông timor',
            'mongolia' => 'mongolia',
            'north korea' => 'bắc triều tiên',
            'south korea' => 'hàn quốc',
            'taiwan' => 'đài loan',
            'hong kong' => 'hồng kông',
            'macau' => 'macau',
            'brazil' => 'brazil',
            'argentina' => 'argentina',
            'chile' => 'chile',
            'peru' => 'peru',
            'colombia' => 'colombia',
            'venezuela' => 'venezuela',
            'ecuador' => 'ecuador',
            'bolivia' => 'bolivia',
            'paraguay' => 'paraguay',
            'uruguay' => 'uruguay',
            'guyana' => 'guyana',
            'suriname' => 'suriname',
            'french guiana' => 'guiana thuộc pháp',
            'falkland islands' => 'quần đảo falkland',
            'south georgia' => 'nam georgia',
            'south sandwich islands' => 'quần đảo nam sandwich',
            'south orkney islands' => 'quần đảo nam orkney',
            'south shetland islands' => 'quần đảo nam shetland',
            'antarctica' => 'nam cực',
            'greenland' => 'greenland',
            'iceland' => 'iceland',
            'faroe islands' => 'quần đảo faroe',
            'svalbard' => 'svalbard',
            'jan mayen' => 'jan mayen',
            'bear island' => 'đảo bear',
            'hopen' => 'hopen',
            'kvitoya' => 'kvitoya',
            'kong karls land' => 'đất kong karls',
            'edgeoya' => 'edgeoya',
            'barentsoya' => 'barentsoya',
            'prins karls forland' => 'prins karls forland',
            'bjornoya' => 'bjornoya',
            'hopen' => 'hopen',
            'kvitoya' => 'kvitoya',
            'kong karls land' => 'đất kong karls',
            'edgeoya' => 'edgeoya',
            'barentsoya' => 'barentsoya',
            'prins karls forland' => 'prins karls forland',
            'bjornoya' => 'bjornoya',
        ];

        // Chuyển text sang lowercase để so sánh
        $lowerText = strtolower($text);
        $result = $text;
        
        // Ưu tiên dịch cụm từ dài trước
        uksort($phraseTranslations, function($a, $b) {
            return strlen($b) - strlen($a);
        });
        
        foreach ($phraseTranslations as $phrase => $translation) {
            $pattern = '/\b' . preg_quote($phrase, '/') . '\b/i';
            if (preg_match($pattern, $result)) {
                $result = preg_replace($pattern, $translation, $result);
            }
        }
        
        // Thử tìm bản dịch chính xác
        if (isset($translations[$text])) {
            return $translations[$text];
        }
        
        // Thử tìm bản dịch lowercase
        if (isset($translations[$lowerText])) {
            return $translations[$lowerText];
        }
        
        // Dịch từng từ
        $words = explode(' ', $result);
        $translatedWords = [];
        
        foreach ($words as $word) {
            $cleanWord = preg_replace('/[^a-zA-Z0-9]/', '', strtolower($word));
            
            if (isset($translations[$cleanWord])) {
                $translatedWords[] = $translations[$cleanWord];
            } else {
                // Giữ nguyên từ không tìm thấy (có thể là tên riêng)
                $translatedWords[] = $word;
            }
        }
        
        $result = implode(' ', $translatedWords);
        
        // Nếu kết quả quá giống với bản gốc, giữ nguyên
        if (strtolower($result) === strtolower($text)) {
            return $text;
        }
        
        return $result;
    }
}

