<?php

namespace Database\Seeders;

use App\Models\Address;
use Illuminate\Database\Seeder;

class AddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Address::create([
            'account_id' => '1',
            'description' => 'restaurant',
            'street_address' => '123 Nguyễn Huệ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7008',
            'latitude' => '10.7740',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '2',
            'description' => 'restaurant',
            'street_address' => '45 Lê Lợi',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6975',
            'latitude' => '10.7758',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '3',
            'description' => 'restaurant',
            'street_address' => '78 Đồng Khởi',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7030',
            'latitude' => '10.7769',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '4',
            'description' => 'restaurant',
            'street_address' => '234 Pasteur',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6878',
            'latitude' => '10.7813',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '5',
            'description' => 'restaurant',
            'street_address' => '567 Võ Văn Tần',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6920',
            'latitude' => '10.7795',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '6',
            'description' => 'restaurant',
            'street_address' => '89 Hai Bà Trưng',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6975',
            'latitude' => '10.7825',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '7',
            'description' => 'restaurant',
            'street_address' => '345 Nguyễn Thị Minh Khai',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6885',
            'latitude' => '10.7870',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '8',
            'description' => 'restaurant',
            'street_address' => '678 Cách Mạng Tháng 8',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 10',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6650',
            'latitude' => '10.7760',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '9',
            'description' => 'restaurant',
            'street_address' => '123 Trần Hưng Đạo',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 5',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6790',
            'latitude' => '10.7545',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '10',
            'description' => 'restaurant',
            'street_address' => '456 Nguyễn Trãi',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 5',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6720',
            'latitude' => '10.7560',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '11',
            'description' => 'restaurant',
            'street_address' => '789 Lý Thường Kiệt',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 10',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6695',
            'latitude' => '10.7725',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '12',
            'description' => 'restaurant',
            'street_address' => '234 Điện Biên Phủ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Bình Thạnh',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7050',
            'latitude' => '10.7990',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '13',
            'description' => 'restaurant',
            'street_address' => '567 Xô Viết Nghệ Tĩnh',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Bình Thạnh',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7100',
            'latitude' => '10.8050',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '14',
            'description' => 'restaurant',
            'street_address' => '890 Nguyễn Văn Trỗi',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Phú Nhuận',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6825',
            'latitude' => '10.7995',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '15',
            'description' => 'restaurant',
            'street_address' => '123 Phan Xích Long',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Phú Nhuận',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6845',
            'latitude' => '10.7980',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '16',
            'description' => 'restaurant',
            'street_address' => '456 Hoàng Văn Thụ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Tân Bình',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6610',
            'latitude' => '10.7990',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '17',
            'description' => 'restaurant',
            'street_address' => '789 Cộng Hòa',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Tân Bình',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6550',
            'latitude' => '10.8010',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '18',
            'description' => 'restaurant',
            'street_address' => '234 Trường Chinh',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Tân Bình',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6420',
            'latitude' => '10.8100',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '19',
            'description' => 'restaurant',
            'street_address' => '567 Lạc Long Quân',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 11',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6380',
            'latitude' => '10.7650',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '20',
            'description' => 'restaurant',
            'street_address' => '890 Âu Cơ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Tân Phú',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6250',
            'latitude' => '10.7850',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '21',
            'description' => 'restaurant',
            'street_address' => '123 Lũy Bán Bích',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Tân Phú',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6320',
            'latitude' => '10.7920',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '22',
            'description' => 'restaurant',
            'street_address' => '456 Phạm Văn Đồng',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Gò Vấp',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6750',
            'latitude' => '10.8420',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '23',
            'description' => 'restaurant',
            'street_address' => '789 Quang Trung',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Gò Vấp',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6650',
            'latitude' => '10.8350',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '24',
            'description' => 'restaurant',
            'street_address' => '234 Nguyễn Oanh',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Gò Vấp',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6820',
            'latitude' => '10.8280',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '25',
            'description' => 'restaurant',
            'street_address' => '567 Phan Văn Trị',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Bình Thạnh',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7020',
            'latitude' => '10.8150',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '26',
            'description' => 'restaurant',
            'street_address' => '890 Nơ Trang Long',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận Bình Thạnh',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.7150',
            'latitude' => '10.8120',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '27',
            'description' => 'restaurant',
            'street_address' => '123 Võ Thị Sáu',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6910',
            'latitude' => '10.7850',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '28',
            'description' => 'restaurant',
            'street_address' => '456 Nam Kỳ Khởi Nghĩa',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6950',
            'latitude' => '10.7780',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '29',
            'description' => 'restaurant',
            'street_address' => '789 Lê Văn Sỹ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6820',
            'latitude' => '10.7920',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '30',
            'description' => 'restaurant',
            'street_address' => '234 Nguyễn Đình Chiểu',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 3',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6890',
            'latitude' => '10.7805',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '31',
            'description' => 'restaurant',
            'street_address' => '567 Trần Quang Khải',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6995',
            'latitude' => '10.7695',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '32',
            'description' => 'restaurant',
            'street_address' => '890 Nguyễn Thái Học',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6920',
            'latitude' => '10.7720',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '33',
            'description' => 'restaurant',
            'street_address' => '123 Tôn Thất Tùng',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6855',
            'latitude' => '10.7750',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '34',
            'description' => 'restaurant',
            'street_address' => '456 Yersin',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6965',
            'latitude' => '10.7735',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '35',
            'description' => 'restaurant',
            'street_address' => '789 Phạm Ngũ Lão',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6915',
            'latitude' => '10.7675',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '36',
            'description' => 'restaurant',
            'street_address' => '234 Bùi Viện',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6925',
            'latitude' => '10.7665',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '37',
            'description' => 'restaurant',
            'street_address' => '567 Đề Thám',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6905',
            'latitude' => '10.7685',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '38',
            'description' => 'restaurant',
            'street_address' => '890 Cô Giang',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6870',
            'latitude' => '10.7650',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '39',
            'description' => 'restaurant',
            'street_address' => '123 Cô Bắc',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 1',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6895',
            'latitude' => '10.7670',
            'added_on' => now(),
        ]);
        Address::create([
            'account_id' => '40',
            'description' => 'restaurant',
            'street_address' => '456 Nguyễn Văn Cừ',
            'city' => 'TP.Hồ Chí Minh',
            'province' => 'Quận 5',
            'postal_code' => '700000',
            'country' => 'Việt Nam',
            'longitude' => '106.6745',
            'latitude' => '10.7590',
            'added_on' => now(),
        ]);
    }
}
